custom: 
  dateOptions: 
    initialMax: 1900
    initialMin: 1880
    max: 1912
    min: 1854
    step: 4
  dateProperty: "ahpo:writingDate"
  displayedProperties: "ahpo:sentBy, ahpo:sentTo, ahpo:citeName"
  initialResource: "http://henripoincare.fr/api/items/5834"
  itemLink: "http://henripoincare.fr/s/correspondance/item/"
  labels: 
    individual: "dcterms:title"
    language: en
    property: "rdfs:label"
  literalDisplayedProperties: "dcterms:subject"
  maxRuleCost: 5
  namespace: "http://e-hp.ahp-numerique.fr/ahpo#"
  pickedProperties: "ahpo:sentBy, ahpo:sentTo, dcterms:subject, ahpo:writtenAt, ahpo:citeName"
  prefixes: "ahpo:<http://e-hp.ahp-numerique.fr/ahpo#>, rdfs:<http://www.w3.org/2000/01/rdf-schema#>, dcterms:<http://purl.org/dc/terms/>, rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
  schemaFile: resources/sqtrl-config/transformationRule.xsd
  sparqlEndpoint: "http://tomcat.henripoincare.fr/fuseki/hp_corpus/sparql/"
  transformationRulesFile: resources/sqtrl-config/ahp-rules.xml
server: 
  address: localhost
  port: 8080
  servlet: 
    context-path: /rdf-navigation-tool
  sessionTimeout: 30
